version: '3'

services:
  web:
    build: .
    command: python /django-audio-recorder-master/django-audio-recorder-master/manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
